=== OTCGS/TCG-Client/Client.Store/Game/Data/Definition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Definition"
    targetNamespace="http://tempuri.org/Definition.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/Definition.xsd"
    xmlns:mstns="http://tempuri.org/Definition.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:element name="Root">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="1">
          <xs:element name="Type" type="mstns:Type" />
          <xs:element name="Enum"   type="mstns:Enum" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Type">
    <xs:sequence>
      <xs:element name="Property" type="mstns:Prop" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:ID" use="required" />
  </xs:complexType>

  <xs:complexType name="Enum">
    <xs:sequence>
      <xs:element name="Value"  type="xs:string" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:ID" use="required" />
  </xs:complexType>

  <xs:complexType name="Prop">
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="IsList" type="xs:boolean" default="false" />
    <xs:attribute name="Type" use="required">
      <xs:simpleType>
        <xs:union memberTypes="mstns:primitiv xs:IDREF">
        </xs:union>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="primitiv">
    <xs:restriction base="xs:string">
      <xs:enumeration value="int32" />
      <xs:enumeration value="int64" />
      <xs:enumeration value="uint32" />
      <xs:enumeration value="uint64" />
      <xs:enumeration value="float32" />
      <xs:enumeration value="float64" />
      <xs:enumeration value="bytes" />
      <xs:enumeration value="uuid" />
      <xs:enumeration value="string" />
      <xs:enumeration value="bool" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== OTCGS/TCG-Client/Game.Data/Protokoll.xml
<?xml version="1.0" encoding="utf-8" ?>
<Root xmlns="http://tempuri.org/Definition.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://tempuri.org/Definition.xsd Definition.xsd">

  <Type Name="PublicKey">
    <Property Name="Modulus" Type="bytes"/>
    <Property Name="Exponent" Type="bytes"/>
  </Type>

  <Enum Name="WhoIsOdd">
    <Value>MeOdd</Value>
    <Value>YouOdd</Value>
  </Enum>

  <Enum Name="DoWeGoOn">
    <Value>GoOn</Value>
    <Value>Abort</Value>
  </Enum>


  <Enum Name="PlayerNumber">
    <Value>None</Value>
    <Value>Player1</Value>
    <Value>Player2</Value>
    <Value>Any</Value>
  </Enum>
  <!-- Mit TOBI GESYNCT-->
  <Type Name="CardInstance">
    <Property Name="Id" Type="uuid" />
    <Property Name="CardDataId" Type="uuid" />
    <Property Name="Creator" Type="PublicKey"/>
    <Property Name="Signature" Type="bytes"/>
  </Type>

  <Type Name="Ruleset ">
    <Property Name="Id" Type="uuid"/>
    <Property Name="Creator" Type="PublicKey"/>
    <Property Name="Name" Type="string"/>
    <Property Name="Revision" Type="int32"/>
    <Property Name="Script" Type="string"/>
    <Property Name="MandatoryKeys" Type="Keys" IsList="true"/>
    <Property Name="Signature" Type="bytes"/>
  </Type>
  
  
  
  <Type Name="Keys">
    <Property Name="Name" Type="string"/>
    <Property Name="Type" Type="string"/>
  </Type>
  
  <Type Name="CardData">
    <Property Name="Id" Type="uuid" />
    <Property Name="Creator" Type="PublicKey"/>
    <Property Name="Edition" Type="string" />
    <Property Name="CardRevision" Type="int32" />
    <Property Name="ImageId" Type="uuid" />
    <Property Name="Name" Type="string" />
    <Property Name="Values" Type="KeyValue" IsList="true" />
    <Property Name="Signature" Type="bytes"/>
  </Type>

  <Type Name="ImageData">
    <Property Name="Id" Type="uuid" />
    <Property Name="Image" Type="bytes" />
    <Property Name="Creator" Type="PublicKey"/>
    <Property Name="Signatur" Type="bytes"/>
  </Type>

  <Type Name="KeyValue">
    <Property Name="Key" Type="string" />
    <Property Name="Value" Type="string" />
  </Type>

  <Type Name="ServerId">
    <Property Name="Name" Type="string"/>
    <Property Name="Key" Type="PublicKey"/>
    <Property Name="Icon" Type="uuid"/>
    <Property Name="Uri" Type="string"/>
    <Property Name="Revision" Type="int32"/>
    <Property Name="Signiture" Type="bytes"/>
  </Type>
  <!-- Mit ENDE TOBI GESYNCT-->


  <!-- Messages für den TradingConnection-->

  <Type Name="TradeOffer">
    <Property Name="Cards" Type="UuidServer" IsList="true"/>
  </Type>

  <Type Name="TradeMessage">
    <Property Name="Text" Type="string"/>
  </Type>

  <Type Name="TradeAgreement">
    <Property Name="CardsGiven" Type="CardInstance" IsList="true"/>
    <Property Name="CardsTaken" Type="CardInstance" IsList="true"/>
  </Type>

  <Type Name="TradeReject">
    <Property Name="CardsGiven" Type="CardInstance" IsList="true"/>
    <Property Name="CardsTaken" Type="CardInstance" IsList="true"/>    
  </Type>
  
  <Type Name="TradeSigning">
    <Property Name="Signiture" Type="bytes"/>
  </Type>
  
  <Type Name="TradeExit" />
  
  <!-- ENDE Messages für den TradingConnection-->


  <!-- Messages für den InformationBrokerConnection des DDR-->

  <Type Name="AskResource">
    <Property Name="Id" Type="UuidServer"/>
    <Property Name="Type" Type="ResourceType"/>
  </Type>

  <Type Name="ResourceNotAvailable">
    <Property Name="Id" Type="UuidServer"/>
    <Property Name="Type" Type="ResourceType"/>
  </Type>

  <Enum Name="ResourceType">
    <Value>ImageData</Value>
    <Value>CardData</Value>
    <Value>CardInstance</Value>
    <Value>Rules</Value>
  </Enum>

  <!-- ENDE Messages für den InformationBrokerConnection des DDR-->

  <!-- Messages Zum Mergen -->

  <Type Name="MergeDataCall">
    <Property Name="Data" Type="bytes"/>
    <Property Name="Index" Type="uint32"/>
  </Type>

  <Type Name="MergeDataReturn">
    <Property Name="Data" Type="bytes"/>
    <Property Name="Index" Type="uint32"/>
  </Type>

  <Type Name="MergeDataOtherFinished"/>



  <!-- ENDE Messages Zum Mergen -->

  <Type Name="UuidServer">
    <Property Name="Uuid" Type="uuid"/>
    <Property Name="Server" Type="PublicKey"/>
  </Type>



  <Type Name="InitData">
    <Property Name="Deck" IsList="true" Type="CardInstance" />
    <Property Name="GameKey" Type="string" />
  </Type>

  <Type Name="Prove">
    <Property Name="Data" Type="string" />
  </Type>

  <Enum Name="Confirmation">
    <Value>Ok</Value>
    <Value>Error</Value>
  </Enum>

  <Type Name="CardPosition">
    <Property Name="Player" Type="PlayerNumber" />
    <Property Name="Region" Type="string" />
    <Property Name="Index" Type="int32" />
  </Type>

  <Type Name="CardSecret">
    <Property Name="Card" Type="CardPosition" />
    <Property Name="Secret" Type="string" />
  </Type>

  <Type Name="AddedCard">
    <Property Name="Position"  Type="CardPosition" />
    <Property Name="CardNumber" Type="int32" />
  </Type>

  <!-- Gamemessages -->

  <Type Name="ShowMessage">
    <Property Name="Message" Type="string"  />
  </Type>

  <Type Name="ChangeText">
    <Property Name="Text" Type="string"  />
  </Type>


  <Type Name="AddCards">
    <Property Name="CardsToAdd" Type="AddedCard" IsList ="true" />
  </Type>

  <Type Name="RemoveCards">
    <Property Name="Position"  Type="CardPosition" IsList="true" />
  </Type>

  <Type Name="ShowCardsToPlayer">
    <Property Name="Cards" Type="CardPosition" IsList="true" />
    <Property Name="PlayerToShow" Type="PlayerNumber" />
  </Type>

  <Type Name="SendSecrets">
    <Property Name="CardSecrets" Type="CardSecret" IsList="true" />
  </Type>

  <Type Name="ShuffleStack">
    <Property Name="Player" Type="PlayerNumber" />
    <Property Name="Region" Type="string" />
  </Type>

  <Type Name="PermutateStack">
    <Property Name="Player" Type="PlayerNumber" />
    <Property Name="Region" Type="string" />
    <Property Name="PermutatedSteak" Type="string" />
  </Type>

  <Type Name="MoveCard">
    <Property Name="From" Type="CardPosition" IsList="true" />
    <Property Name="To" Type="CardPosition" IsList="true" />
  </Type>

  <Type Name="GenerateRandomNumber">
    <Property Name="HashedNumber" Type="bytes" />
  </Type>

  <Type Name="RandomNumber">
    <Property Name="Value" Type="uint32" />
  </Type>

  <Type Name="SetNumber">
    <Property Name="Name" Type="string" />
    <Property Name="Value" Type="int32" />
  </Type>

  <Type Name="SetString">
    <Property Name="Name" Type="string" />
    <Property Name="Value" Type="string" />
  </Type>

  <Type Name="TurnEnd" />
</Root>

=== OTCGS/TCG-Client/Misc.Generator/Protokoll.xml
<?xml version="1.0" encoding="utf-8" ?>
<Root xmlns="http://tempuri.org/Definition.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://tempuri.org/Definition.xsd Definition.xsd">

  <Type Name="Certificate">
    <Property Type="uuid" Name="UserId" />
    <Property Type="uuid" Name="CertificateId" />
    <Property Type="Key" Name="Key" />
    <Property Type="CertSignature" IsList="true" Name="Signatures" />
  </Type>
  <Type Name="Key">
    <Property Name="Modulus" Type="bytes" />
    <Property Name="Exponent" Type="bytes" />
  </Type>
  <Type Name="CardSignature">
    <Property Name="Signee" Type="uuid" />
    <Property Name="CertificateId" Type="uuid" />
    <Property Name="Value" Type="bytes" />
  </Type>
  <Type Name="CertSignature">
    <Property Name="Signee" Type="uuid" />
    <Property Name="CertificateId" Type="uuid" />
    <Property Name="Value" Type="bytes" />
  </Type>
  <Type Name="Card">
	<Property Type="uuid" Name="Archetype" />
    <Property Type="uuid" Name="CardId" />
    <Property Type="CardSignature" IsList="true" Name="Signatures" />
  </Type>

  <Type Name="Error">
    <Property Type="string" Name="ErrorMessage" />
  </Type>
  <Type Name="GetAliasRequest">
    <Property Type="uuid" Name="Uuid" />
  </Type>
  <Type Name="GetAliasResponse">
    <Property Type="string" Name="Alias" />
  </Type>
  <Type Name="CreateAccountRequest">
    <Property Type="string" Name="Email" />
    <Property Type="string" Name="Password" />
  </Type>
  <Type Name="CreateAccountResponse">
    <Property Type="uuid" Name="Uuid" />
  </Type>

  <Type Name="DeleteAccountRequest">
  </Type>
  <Type Name="DeleteAccountResponse">
  </Type>

  <Type Name="GetUserIdRequest">
  </Type>
  <Type Name="GetUserIdResponse">
    <Property Type="uuid" Name="Uuid" />
  </Type>

  <Type Name="GetServerCertificateRequest">
  </Type>
  <Type Name="GetServerCertificateResponse">
    <Property Type="Certificate" Name="Certificate" />
  </Type>

  <Type Name="GetUserCertificateRequest">
  </Type>
  <Type Name="GetUserCertificateResponse">
    <Property Type="Certificate" Name="Certificate" />
  </Type>
</Root>
